version: '3'

services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redisdata:/data

  datacube-database:
    image: postgres
    container_name: datacube-database
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./dbdump.sql:/docker-entrypoint-initdb.d/02-dbdump.sql
    environment:
      - POSTGRES_DB=datacube
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localuser1234

  cubequery-worker:
    build: ./worker.Dockerfile
    image: cubequery-deploy-worker:latest
    environment:
      - REDIS_URL=redis://redis-master:6379/
      - AWS_NO_SIGN_REQUEST=yes
      - AWS_VIRTUAL_HOSTING=FALSE
      - AWS_S3_ENDPOINT=s3-uk-1.sa-catapult.co.uk
    restart: always
    volumes:
      - ./processes:/processes/processes
      - ./outputdata:/data
      - c:\\git\\cubequery:/app

  cubequery-server:
    build: ./server.Dockerfile
    image: cubequery-deploy-server:latest
    restart: always
    environment:
      - REDIS_URL=redis://redis-master:6379/
      - APP_DEBUG=true
    ports:
      - "5000:5000"
    volumes:
      - ./processes:/processes/processes
      - ./outputdata:/data
      - c:\\git\\cubequery:/app
